### ISSUE TITLE
Transcriber with engine name `whisper` not found

### ISSUE THREAD

**Issue by wmccuddy** [psychopy/psychopy-whisper#3]
Recently downloaded PsychoPy v 2024.1.4 along with the psychopy-whisper from the plugin gui. 

Tried setting up simple paradigm to detect and transcribe speech with the builder gui (added microphone as input, selected transcribe box and added whisper as engine along with a specific model). After generating and running the python script created by the builder I get the error "Transcriber with engine name `whisper` not found" Full output with error below.

if i try to import whisper from the python console, it is not there. However, importing pyschopy_whisper shows that the plugin was installed in the same python environment used my psychopy. 

`###################### Running: C:\Users\wmccuddy\test.py ######################
pygame 2.1.0 (SDL 2.0.16, Python 3.8.10)
Hello from the pygame community. https://www.pygame.org/contribute.html

  File "C:\Program Files\PsychoPy\lib\site-packages\psychopy\sound\transcribe.py", line 754, in getTranscriberInterface
    transcriber = transcribers[engine]
KeyError: 'whisper'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\wmccuddy\test.py", line 680, in <module>
    run(
  File "C:\Users\wmccuddy\test.py", line 371, in run
    setupTranscriber(
  File "C:\Program Files\PsychoPy\lib\site-packages\psychopy\sound\transcribe.py", line 798, in setupTranscriber
    transcriber = getTranscriberInterface(engine)
  File "C:\Program Files\PsychoPy\lib\site-packages\psychopy\sound\transcribe.py", line 756, in getTranscriberInterface
    raise ValueError(
ValueError: Transcriber with engine name `whisper` not found.
################ Experiment ended with exit code 1 [pid:28336] #################`

**Comment by TEParsons** [comment]
I think this may be as simple as a capitalization error (`whisper` vs `Whisper`). I can't find the PR fixing it, but I think this is fixed in the dev branch of psychopy, so should be fixed in the upcoming release.
